### PR TITLE
Reduce scope of members

### LINKED ISSUE #214: Use minimum scope for members throughout the code base
Many members of classes have the improper/no access modifier set. It is always a good practice to use the minimum scope for these.

### PR DESCRIPTION
**Pull request by macdude357**
* Reduce scope of members for issue #214

Closes #214 

#### What has been done to verify that this works as intended?
Code compiles and tests pass
#### Why is this the best possible solution? Were any other approaches considered?
Used IntelliJ's code inspection to find members that could be changed to a more restrictive scope.
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
None
#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No

### CODE REVIEW

**Comment by macdude357** [comment]
Sorry about that.  I fixed my compile issues but branch master had an existing compile error that I don't know how to fix since it requires a new arg and I'm not sure what to put there:

briefcase/model/form/FormMetadataCommandsTest.java:82: error: method orElseThrow in class Optional<T> cannot be applied to given types;
          FormMetadata actualFormMetadata = formMetadataPort.fetch(key).orElseThrow();

**Comment by ggalmazor** [comment]
You're right, @macdude357, sorry about that. It looks like I slipped some errors into master without noticing. I'm working on a v2.0 branch that sets the source language level to Java 11 and those errors you're getting are because the master branch has to be compiled at a language level of Java 8. I'll work on a solution asap so that you can rebase your branch and we can process this PR.

**Comment by ggalmazor** [comment]
Hi @macdude357! You should rebase master into your branch to solve the issues with mismatching java language level calls.

**Comment by macdude357** [comment]
I'll update the PR to get the code coverage numbers back up.

**Comment by ggalmazor** [comment]
> I'll update the PR to get the code coverage numbers back up.

I wouldn't worry about it.

**Comment by ggalmazor** [comment]
I'll tag this one to be released in v1.8 because this PR can't be tested without a full regression test, which we only do in minor releases (going from v1.17 to v1.18)

**Comment by ggalmazor** [comment]
So, we decided to ship this in v1.17.2.

@kkrawczyk123, when testing this one, please, try to go through the normal use cases to ensure this PR doesn't break basic functionality. One platform (Windows) and One server (Aggregate on Tomcat) would be enough.

**Comment by kkrawczyk123** [comment]
**Testes with success!**
None regression has been identified on Windows. (according to the comment above)

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior identified"

**Comment by kkrawczyk123** [comment]
@opendatakit-bot label "behavior verified"
